name: Build and deploy GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: pages
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # подберите подходящую версию если нужно

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build site with Jekyll
        run: bundle exec jekyll build --destination _site

      - name: Add .nojekyll (prevent Jekyll on Pages if you need)
        run: touch _site/.nojekyll

      - name: Fix .md links to .html in generated HTML
        run: |
          BUILD_DIR="_site"
          echo "Post-processing HTML files in $BUILD_DIR"
          # Заменяет href="path.md" -> href="path.html" (с сохранением якорей)
          find "$BUILD_DIR" -type f -name '*.html' -print0 \
            | xargs -0 sed -E -i 's/(href="[^"]+)\.md(#[-a-zA-Z0-9_]+)?(")/\1.html\2\3/g'

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
